-- 1. Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DNUM INT PRIMARY KEY,
    DName VARCHAR(30) NOT NULL UNIQUE,
    ManagerSSN CHAR(9) NOT NULL UNIQUE,
    ManagerStartDate DATE NOT NULL
);

-- 2. Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
    SSN CHAR(9) PRIMARY KEY,
    Fname VARCHAR(30) NOT NULL,
    Lname VARCHAR(30) NOT NULL,
    BirthDate DATE NOT NULL,
    Gender CHAR(1) NOT NULL CHECK (Gender IN ('M','F')),
    DNO INT NOT NULL,
    SupervisorSSN CHAR(9),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUM),
    FOREIGN KEY (SupervisorSSN) REFERENCES EMPLOYEE(SSN)
);

-- 3. Add foreign key constraint for ManagerSSN in DEPARTMENT (after EMPLOYEE created)
ALTER TABLE DEPARTMENT
ADD CONSTRAINT fk_manager FOREIGN KEY (ManagerSSN) REFERENCES EMPLOYEE(SSN);

-- 4. Create DEPT_LOCATIONS table (for multiple locations per department)
CREATE TABLE DEPT_LOCATIONS (
    DNUM INT NOT NULL,
    Location VARCHAR(40) NOT NULL,
    PRIMARY KEY (DNUM, Location),
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

-- 5. Create PROJECT table
CREATE TABLE PROJECT (
    PNumber INT PRIMARY KEY,
    PName VARCHAR(30) NOT NULL,
    Location VARCHAR(40),
    DNUM INT NOT NULL,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

-- 6. Create WORKS_ON table (many-to-many between EMPLOYEE and PROJECT)
CREATE TABLE WORKS_ON (
    SSN CHAR(9) NOT NULL,
    PNumber INT NOT NULL,
    Hours DECIMAL(4,1) NOT NULL,
    PRIMARY KEY (SSN, PNumber),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNumber) REFERENCES PROJECT(PNumber)
);

-- 7. Create DEPENDENT table
CREATE TABLE DEPENDENT (
    SSN CHAR(9) NOT NULL,
    DependentName VARCHAR(30) NOT NULL,
    Gender CHAR(1) NOT NULL CHECK (Gender IN ('M','F')),
    BirthDate DATE NOT NULL,
    PRIMARY KEY (SSN, DependentName),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN) ON DELETE CASCADE
);